In [1]:
import numpy as np

In [2]:
d=np.array([10,40,50,30,70])
d

array([10, 40, 50, 30, 70])

In [3]:
np.mean(d)

40.0

In [4]:
np.median(d)

40.0

In [5]:
np.var(d)

400.0

In [6]:
np.std(d)

20.0

In [7]:
np.max(d)

70

In [8]:
np.min(d)

10

In [9]:
np.quantile(d,0.25)

30.0

In [11]:
r=np.random.rand(10,5)
r

array([[0.63594174, 0.02229819, 0.56249136, 0.42698838, 0.70251453],
       [0.2217897 , 0.86351659, 0.02988997, 0.17818153, 0.8692328 ],
       [0.27372993, 0.88371419, 0.56199186, 0.97033566, 0.4410613 ],
       [0.30485547, 0.5042915 , 0.27830456, 0.17803805, 0.96100433],
       [0.26558248, 0.25486944, 0.01407395, 0.8009936 , 0.40744768],
       [0.2933841 , 0.78621081, 0.01532261, 0.0632855 , 0.52222884],
       [0.31891322, 0.71633951, 0.21097571, 0.01076948, 0.85514686],
       [0.60020417, 0.70829165, 0.96556575, 0.49873106, 0.94763822],
       [0.38346664, 0.03993535, 0.16379035, 0.05380117, 0.87616807],
       [0.30029316, 0.32551399, 0.98795196, 0.59379844, 0.50929094]])

In [12]:
r=np.random.rand()
r

0.1319678082411554

In [13]:
r=np.random.rand(100)
r

array([0.56262915, 0.0609595 , 0.33984725, 0.08596427, 0.22093844,
       0.24391356, 0.38084195, 0.20539096, 0.26587684, 0.18170126,
       0.62318713, 0.27364215, 0.15912373, 0.8571289 , 0.23974515,
       0.48925127, 0.30723624, 0.49333334, 0.63653199, 0.89769337,
       0.56445643, 0.1422047 , 0.98706415, 0.5562935 , 0.72011189,
       0.71687038, 0.84304786, 0.37410104, 0.97034591, 0.10999357,
       0.55111779, 0.66466692, 0.88131516, 0.95193863, 0.93487793,
       0.50402003, 0.78545115, 0.42511683, 0.61997381, 0.97327381,
       0.73867985, 0.60333965, 0.41284202, 0.66464227, 0.71961151,
       0.03749407, 0.1084895 , 0.98517426, 0.23049654, 0.49686154,
       0.59283056, 0.37820296, 0.74068719, 0.86744657, 0.04684441,
       0.60106029, 0.53637086, 0.88483492, 0.49443934, 0.41003251,
       0.27559289, 0.11246668, 0.2993935 , 0.21499968, 0.18987367,
       0.52163394, 0.4864013 , 0.71408301, 0.38990761, 0.48038377,
       0.31923767, 0.01215578, 0.21062473, 0.36740675, 0.30632

In [14]:
r=np.random.rand(5,3,2)
r

array([[[0.24317985, 0.39681073],
        [0.18553914, 0.78829482],
        [0.67919152, 0.08140629]],

       [[0.49001052, 0.35778814],
        [0.01036931, 0.80588654],
        [0.35973183, 0.02773978]],

       [[0.70650304, 0.24615809],
        [0.25635046, 0.11654433],
        [0.70894462, 0.84215047]],

       [[0.57821418, 0.20720562],
        [0.32151674, 0.82569722],
        [0.05608307, 0.15232881]],

       [[0.57491239, 0.0139629 ],
        [0.30644627, 0.96162406],
        [0.38736021, 0.24377022]]])

In [15]:
r=np.random.randn(10,4)
r

array([[-0.46015416, -0.53255931, -1.47708523, -1.1846657 ],
       [-0.30401694,  0.2075135 , -0.2085874 ,  2.56186357],
       [-1.46750759, -0.81005068, -0.41583458,  1.56414779],
       [-1.17606068,  0.49464381, -0.40170097,  1.03170534],
       [-1.30892921,  0.11013359, -1.07100828, -0.34556578],
       [-2.07544765,  0.45468253, -0.19447968,  0.16469183],
       [-2.6735259 , -2.36567737,  0.17126669, -0.62287681],
       [-0.57137677, -1.11453904,  1.27451294, -0.80861397],
       [ 1.07234529,  0.16226096, -0.61072474, -2.19679053],
       [ 0.39906214, -0.66019501, -1.4773126 , -0.43588788]])

In [16]:
np.random.normal(10,2,(7,4))

array([[13.50558299, 10.15252336, 13.30737093, 14.85772975],
       [12.48363049,  6.93235642, 11.46924257,  7.13479273],
       [10.35153187,  9.49353735,  9.25499464, 10.17475178],
       [ 8.38860668,  6.95827447,  9.60830267, 10.99997588],
       [ 8.56324622, 13.7145015 ,  6.04191234,  8.07984775],
       [ 9.97497203, 11.93394828,  6.51739427, 10.99978964],
       [ 6.14425122, 11.33984322, 10.21700167,  6.32771621]])

In [19]:
np.random.randint(35,86,20)

array([57, 55, 84, 80, 84, 44, 75, 73, 85, 36, 84, 62, 72, 54, 60, 82, 48,
       47, 79, 45])

In [22]:
np.random.randint(35,86,200)

array([81, 80, 64, 59, 43, 55, 84, 36, 81, 74, 55, 61, 49, 84, 35, 53, 41,
       54, 37, 85, 45, 38, 48, 58, 65, 77, 65, 82, 44, 62, 48, 78, 47, 68,
       46, 74, 47, 52, 41, 83, 81, 41, 75, 83, 71, 40, 50, 48, 61, 35, 43,
       54, 68, 72, 72, 51, 79, 50, 82, 36, 75, 81, 44, 52, 50, 75, 45, 48,
       81, 66, 70, 85, 53, 69, 67, 59, 61, 61, 69, 58, 43, 57, 54, 58, 36,
       83, 85, 38, 57, 61, 53, 82, 55, 75, 63, 70, 40, 53, 45, 52, 65, 38,
       70, 78, 39, 50, 36, 58, 52, 45, 66, 55, 83, 55, 40, 62, 61, 84, 47,
       63, 78, 48, 68, 66, 48, 42, 57, 36, 77, 45, 66, 45, 60, 74, 54, 42,
       85, 57, 57, 45, 80, 46, 43, 58, 51, 72, 57, 82, 70, 38, 72, 37, 66,
       68, 69, 68, 55, 42, 36, 68, 41, 45, 80, 69, 71, 74, 38, 44, 51, 66,
       66, 58, 46, 57, 41, 36, 83, 38, 45, 84, 72, 58, 48, 82, 48, 51, 79,
       81, 68, 84, 50, 43, 69, 66, 81, 66, 62, 50, 45, 42])

In [23]:
np.random.randint(35,86,5)

array([73, 58, 79, 68, 59])