In [2]:
h=[30,20,5,8,9]
h

[30, 20, 5, 8, 9]

In [3]:
import numpy as np
h

[30, 20, 5, 8, 9]

In [4]:
import numpy as np
s=(6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [8]:
import numpy as np
[s]

[(6, 2, 3, 9, 7, 5, 8)]

In [13]:
y=list(s)
k=[]
for i in y:
    k.append(i**2)
s=tuple(k)
s

(36, 4, 9, 81, 49, 25, 64)

In [14]:
tuple(x**2 for x in s)

(1296, 16, 81, 6561, 2401, 625, 4096)

In [17]:
s

(36, 4, 9, 81, 49, 25, 64)

In [18]:
s = (36, 4, 9, 81, 49, 25, 64)
greater_than_30 = [x for x in s if x > 30]
print(greater_than_30)


[36, 81, 49, 64]


In [27]:
import numpy as np
arr=np.array([20,50,30,70,80,40,36,54,23,98])
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [28]:
arr+5

array([ 25,  55,  35,  75,  85,  45,  41,  59,  28, 103])

In [29]:
arr>50

array([False, False, False,  True,  True, False, False,  True, False,
        True])

In [30]:
arr[arr>50]

array([70, 80, 54, 98])

In [31]:
np.where(arr>50)

(array([3, 4, 7, 9], dtype=int64),)